"""add_user_name_phone

Revision ID: 1e52778d5205
Revises: 20260504_0005
Create Date: 2026-05-04 10:45:48.165592
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '1e52778d5205'
down_revision: Union[str, None] = '20260504_0005'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('full_name', sa.String(length=140), nullable=True))
    op.add_column('users', sa.Column('phone', sa.String(length=40), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone')
    op.drop_column('users', 'full_name')
    # ### end Alembic commands ###

